// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('i18n', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
    await driver.get("http://localhost:3000/")
  })
  afterEach(async function() {
    await driver.quit();
  })

  it('vi', async function() {
    await driver.findElement(By.xpath("//*[text()='VI']")).click()
    await driver.wait(until.urlContains('vi'))
    await checkExistsWithText('Giỏ Hàng')
    await checkExistsWithText('Quán Nhỏ')
    await checkExistsWithText('Cà phê nóng')
  })


  it('en', async function() {
    await driver.findElement(By.xpath("//*[text()='EN']")).click()
    await driver.wait(until.urlContains('en'))
    await checkExistsWithText('Cart')
    await checkExistsWithText('Cafeteria')
    await checkExistsWithText('Hot coffee')
  })


  async function checkExistsWithText(text){
    const elements = await driver.findElements(By.xpath(`//*[text()='${text}']`))
    assert(elements.length)
  }

  
})
